base: /
baseVariants:
  -
    base: 'https://govt3dd.ddev.site/'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: DE
    enabled: true
    base: /
    typo3Language: de
    locale: de-DE.utf8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
    solr_core_read: gov_de
    languageId: 0
rootPageId: 1
solr_enabled_read: true
solr_host_read: '%env(SOLR_HOST)%'''
solr_path_read: /
solr_port_read: '8983'
solr_scheme_read: http
solr_use_write_connection: false
websiteTitle: ''
