changelog:
  exclude:
    labels:
      - duplicate
      - 'good first issue'
      - 'help wanted'
      - invalid
      - question
      - wontfix
  categories:
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 🚀 Improved
      labels:
        - enhancement
    - title: 🚑 Fixed
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"
